import { memo } from 'react';
import { Film, Plus, Search, Trash2, Upload } from 'lucide-react';
import type { FilmStock } from '../../../../db/schema';
import type { TranslationKey } from '../../../../i18n/translations';
import { EmptyState } from '../../../../components/EmptyState';
import { IconButton } from '../../../../components/ui/IconButton';
import { FilmSvgAvatar } from '../../../../components/FilmSvgAvatar';
import type { GearSort } from '../shared/gearListUtils';
import { useFilteredGearItems } from '../shared/gearListUtils';

type Translate = (key: TranslationKey, values?: Record<string, string | number>) => string;
interface FilmStocksTabProps { filmStocks: readonly FilmStock[]; searchQuery: string; sortBy: GearSort; t: Translate; uploadingEntityId: string | null; onAdd: () => void; onEdit: (film: FilmStock) => void; onDelete: (id: string) => void; onUpload: (id: string) => void; onPreview: (url: string) => void; onAdjustStock: (id: string, delta: number) => void; }
const getAvatarUrl = (url?: string | null) => url && (url.startsWith('http') || url.startsWith('data:') || url.startsWith('blob:')) ? url : null;

export const FilmStocksTab = memo(({ filmStocks, searchQuery, sortBy, t, uploadingEntityId, onAdd, onEdit, onDelete, onUpload, onPreview, onAdjustStock }: FilmStocksTabProps) => {
  const displayFilms = useFilteredGearItems(filmStocks, searchQuery, sortBy);
  if (filmStocks.length === 0 || displayFilms.length === 0) return <div className="lenses-grid-layout"><div style={{ height: '50vh', gridColumn: '1 / -1', display: 'flex', alignItems: 'center' }}><EmptyState icon={Film} title={filmStocks.length === 0 ? t('gear.noFilmTitle') : t('gear.noFilmMatch')} description={filmStocks.length === 0 ? t('gear.noFilmDesc') : t('gear.noMatchDesc')} action={filmStocks.length === 0 ? <button className="primary" onClick={onAdd}><Plus size={16} /> {t('gear.addFilmStock')}</button> : undefined} /></div></div>;
  return <div className="lenses-grid-layout">{displayFilms.map(film => {
    const avatarUrl = getAvatarUrl(film.avatarUrl);
    return <div key={film.id} className="gear-card lens-card-horizontal" onClick={() => onEdit(film)} style={{ cursor: 'pointer' }}><div className="camera-avatar-container" style={{ width: '80px', height: '80px' }}>{avatarUrl ? <img src={avatarUrl} alt={film.name} className="camera-avatar-img" onClick={event => { event.stopPropagation(); onPreview(avatarUrl); }} title={t('gear.previewCover')} style={{ objectFit: 'cover' }} /> : <div className="lens-card-avatar" style={{ padding: '4px', width: '100%', height: '100%', overflow: 'hidden', margin: 0 }}><FilmSvgAvatar brand={film.brand} name={film.name} format={film.format} size={72} /></div>}<button type="button" className="camera-avatar-upload-overlay" onClick={event => { event.stopPropagation(); if (avatarUrl) onPreview(avatarUrl); else onUpload(film.id!); }} disabled={uploadingEntityId === film.id} title={avatarUrl ? t('gear.previewCover') : t('gear.uploadFilmCover')}>{uploadingEntityId === film.id ? <span className="avatar-loading-spinner" /> : avatarUrl ? <Search size={14} /> : <Upload size={14} />}</button></div><div className="lens-card-content"><div className="gear-card-header"><span className={`tag ${film.colorType === 'color' ? 'color' : 'bw'}`}>{film.colorType === 'color' ? t('gear.color') : t('gear.bw')}</span><IconButton variant="danger" icon={<Trash2 size={16} />} title={t('gear.deletePermanently')} onClick={event => { event.stopPropagation(); onDelete(film.id!); }} /></div><h3 style={{ margin: '4px 0' }}>{film.brand} {film.name}</h3><div className="gear-details" style={{ display: 'flex', flexDirection: 'column', gap: '4px', borderTop: 'none', paddingTop: '0', marginTop: '0' }}><div style={{ display: 'flex', gap: '16px', fontSize: '12px' }}><div><strong>ISO:</strong>{film.iso}</div><div><strong>{t('gear.format')}:</strong> {film.format}</div></div><div style={{ marginTop: '4px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', width: '100%' }}><span style={{ fontSize: '12px', color: 'var(--text-secondary)' }}><strong>{t('gear.stockCount')}:</strong> {t('gear.rollsInStock', { count: film.stockCount || 0 })}</span><div style={{ display: 'flex', gap: '6px' }}><button type="button" className="secondary" style={{ padding: '2px 8px', fontSize: '11px', minWidth: '22px', height: '22px', width: 'auto', display: 'flex', alignItems: 'center', justifyContent: 'center' }} title={t('gear.decreaseStock')} onClick={event => { event.stopPropagation(); onAdjustStock(film.id!, -1); }}>-</button><button type="button" className="secondary" style={{ padding: '2px 8px', fontSize: '11px', minWidth: '22px', height: '22px', width: 'auto', display: 'flex', alignItems: 'center', justifyContent: 'center' }} title={t('gear.increaseStock')} onClick={event => { event.stopPropagation(); onAdjustStock(film.id!, 1); }}>+</button></div></div></div></div></div>;
  })}</div>;
});
